const translations = { 
    en : { 
        locale : "en-US",
        welcome: "Welcome",
        home: "Home",
        reservation: "Reservation",
        profil: "Profil",
        contact: "Contact",
        myInformation : "My information",
        changePassword: "Change Password",
        email: "Email",
        password : "Password",
        confirmPassword : "Confirm Password",
        invalidEmail : "Invalid email",
        invalidPassword: "Please enter valid password",
        passwordsNotMatch : "Passwords does not match",
        requiredEmail : "Please enter email adress",
        requiredPassword : "Please enter password",
        emailNotRegistered : "Email not registered",
        emailRegistered: "Email already registered",
        passwordUpdate : "Password have been successfully updated! ✅",
        informationUpdated : "Information have been successfully updated! ✅",
        informationUpdatedDetails: "Don't forget to check your email address if you have updated it.",
        connectionFailure : "Connection Failure ⛔️",
        connectionFailureDetails : "Sorry, our service is not available or you do not have an internet connection.",
        wrongInformation : "Wrong password or email",
        createAccount: "Create new account",
        signIn : "Sign In",
        login : "Login",
        register : "Register",
        tooShort : "Too Short!",
        tooLong: "Too Long!",
        requiredName : "Please enter full name",
        required : "Required",
        registrationComplete : "Registration complete! 🎉",
        registrationCompleteDetails : "Please check your inbox to confirm your email and start exploring.",
        unexpectedError : "Unexpected error occurred",
        tryLater : "Try later",
        firstName : "First Name",
        lastName: "Last Name",
        birthday : "Date of Birth",
        submit : "Submit",
        settings : "Settings",
        newReservation : 'New Reservation',
        addReservation : "Add reservation",
        logout : "Logout",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        reserved : "Reserved",
        noReservation : "No Reservation.",
        confirmReservation : "Confirm Reservation",
        confirmReservatiojnDetails : "Please check the date and times",
        reservationConfirm : "Reservation confirmed! 🎾",
        reservationConfirmDetails: "Make sure you're ready to play and enjoy your time on the court!",
        reservationFailure : "Slot not available ⛔️",
        reservationFailureDetails: "Sorry, the time slot you selected is no longer available. Please choose another time slot.",
        court : "Court",
        start : "Start",
        end: "End",
        minimumHour: "Minimum 1 hour",
        date: "Date"
    },
    fr: {
        locale: "fr-FR",
        welcome: "Bienvenue",
        home: "Accueil",
        reservation: "Réservation",
        profil: "Profil",
        contact: "Contact",
        myInformation : "Mes informations",
        changePassword: "Changer le mot de passe",
        email: "Email",
        password : "Mot de passe",
        confirmPassword : "Confirmer le mot de passe",
        invalidEmail : "Email invalide",
        invalidPassword: "Veuillez entrer un mot de passe valide",
        passwordsNotMatch : "Les mots de passe ne correspondent pas",
        requiredEmail : "Veuillez entrer une adresse email",
        requiredPassword : "Veuillez entrer un mot de passe",
        emailNotRegistered : "Email non enregistré",
        emailRegistered: "Email déjà enregistré",
        passwordUpdate : "Le mot de passe a été mis à jour avec succès ! ✅",
        informationUpdated : "Les informations ont été mises à jour avec succès ! ✅",
        informationUpdatedDetails: "N'oubliez pas de vérifier votre adresse email si vous l'avez mise à jour.",
        connectionFailure : "Échec de la connexion ⛔️",
        connectionFailureDetails : "Désolé, notre service n'est pas disponible ou vous n'avez pas de connexion internet.",
        wrongInformation : "Mot de passe ou email incorrect",
        createAccount: "Créer un nouveau compte",
        signIn : "Se connecter",
        login : "Connexion",
        register : "S'inscrire",
        tooShort : "Trop court !",
        tooLong: "Trop long !",
        requiredName : "Veuillez entrer votre nom complet",
        required : "Requis",
        registrationComplete : "Inscription terminée ! 🎉",
        registrationCompleteDetails : "Veuillez vérifier votre boîte de réception pour confirmer votre email et commencer à explorer.",
        unexpectedError : "Une erreur inattendue s'est produite",
        tryLater : "Réessayez plus tard",
        firstName : "Prénom",
        lastName: "Nom",
        birthday : "Date de naissance",
        submit : "Envoyer",
        settings : "Paramètres",
        newReservation : 'Nouvelle réservation',
        addReservation : "Ajouter une réservation",
        logout : "Déconnexion",
        darkMode: "Mode sombre",
        lightMode: "Mode clair",
        reserved : "Réservé",
        noReservation : "Aucune réservation.",
        confirmReservation : "Confirmer la réservation",
        confirmReservationDetails : "Veuillez vérifier la date et l'heure",
        reservationConfirm : "Réservation confirmée ! 🎾",
        reservationConfirmDetails: "Assurez-vous d'être prêt à jouer et de profiter de votre temps sur le court !",
        reservationFailure : "Créneau non disponible ⛔️",
        reservationFailureDetails: "Désolé, le créneau horaire que vous avez sélectionné n'est plus disponible. Veuillez choisir un autre créneau horaire.",
        court : "Court",
        start : "Début",
        end: "Fin",
        minimumHour: "Minimum 1 heure",
        date: "Date"
    },
    es: {
        locale: "es-ES",
        welcome: "Bienvenido",
        home: "Inicio",
        reservation: "Reserva",
        profil: "Perfil",
        contact: "Contacto",
        myInformation : "Mis datos",
        changePassword: "Cambiar contraseña",
        email: "Correo electrónico",
        password : "Contraseña",
        confirmPassword : "Confirmar contraseña",
        invalidEmail : "Correo electrónico inválido",
        invalidPassword: "Por favor, introduzca una contraseña válida",
        passwordsNotMatch : "Las contraseñas no coinciden",
        requiredEmail : "Por favor, introduzca una dirección de correo electrónico",
        requiredPassword : "Por favor, introduzca una contraseña",
        emailNotRegistered : "Correo electrónico no registrado",
        emailRegistered: "Correo electrónico ya registrado",
        passwordUpdate : "¡La contraseña se ha actualizado correctamente! ✅",
        informationUpdated : "¡La información se ha actualizado correctamente! ✅",
        informationUpdatedDetails: "No olvide verificar su dirección de correo electrónico si la ha actualizado.",
        connectionFailure : "Error de conexión ⛔️",
        connectionFailureDetails : "Lo siento, nuestro servicio no está disponible o no tiene conexión a internet.",
        wrongInformation : "Contraseña o correo electrónico incorrectos",
        createAccount: "Crear nueva cuenta",
        signIn : "Iniciar sesión",
        login : "Iniciar sesión",
        register : "Registrarse",
        tooShort : "¡Demasiado corto!",
        tooLong: "¡Demasiado largo!",
        requiredName : "Por favor, introduzca el nombre completo",
        required : "Requerido",
        registrationComplete : "¡Registro completado! 🎉",
        registrationCompleteDetails : "Por favor, compruebe su bandeja de entrada para confirmar su correo electrónico y comenzar a explorar.",
        unexpectedError : "Se produjo un error inesperado",
        tryLater : "Inténtelo más tarde",
        firstName : "Nombre",
        lastName: "Apellido",
        birthday : "Fecha de nacimiento",
        submit : "Enviar",
        settings : "Ajustes",
        newReservation : 'Nueva reserva',
        addReservation : "Agregar reserva",
        logout : "Cerrar sesión",
        darkMode: "Modo oscuro",
        lightMode: "Modo claro",
        reserved : "Reservado",
        noReservation : "Sin reservas.",
        confirmReservation : "Confirmar reserva",
        confirmReservatiojnDetails : "Por favor, compruebe la fecha y hora",
        reservationConfirm : "¡Reserva confirmada! 🎾",
        reservationConfirmDetails: "¡Asegúrese de estar listo para jugar y disfrutar de su tiempo en la cancha!",
        reservationFailure : "Ranura no disponible ⛔️",
        reservationFailureDetails: "Lo sentimos, el horario que seleccionó ya no está disponible. Por favor, elija otro horario.",
        court : "Cancha",
        start : "Inicio",
        end: "Fin",
        minimumHour: "Mínimo 1 hora",
        date: "Fecha"
    },
    de: {
        locale: "de-DE",
        welcome: "Willkommen",
        home: "Startseite",
        reservation: "Reservierung",
        profil: "Profil",
        contact: "Kontakt",
        myInformation : "Meine Informationen",
        changePassword: "Passwort ändern",
        email: "E-Mail",
        password : "Passwort",
        confirmPassword : "Passwort bestätigen",
        invalidEmail : "Ungültige E-Mail",
        invalidPassword: "Bitte geben Sie ein gültiges Passwort ein",
        passwordsNotMatch : "Passwörter stimmen nicht überein",
        requiredEmail : "Bitte geben Sie eine E-Mail-Adresse ein",
        requiredPassword : "Bitte geben Sie ein Passwort ein",
        emailNotRegistered : "E-Mail nicht registriert",
        emailRegistered: "E-Mail bereits registriert",
        passwordUpdate : "Passwort wurde erfolgreich aktualisiert! ✅",
        informationUpdated : "Informationen wurden erfolgreich aktualisiert! ✅",
        informationUpdatedDetails: "Vergessen Sie nicht, Ihre E-Mail-Adresse zu überprüfen, wenn Sie sie aktualisiert haben.",
        connectionFailure : "Verbindungsfehler ⛔️",
        connectionFailureDetails : "Entschuldigung, unser Service ist nicht verfügbar oder Sie haben keine Internetverbindung.",
        wrongInformation : "Falsches Passwort oder falsche E-Mail",
        createAccount: "Neues Konto erstellen",
        signIn : "Anmelden",
        login : "Anmelden",
        register : "Registrieren",
        tooShort : "Zu kurz!",
        tooLong: "Zu lang!",
        requiredName : "Bitte geben Sie den vollständigen Namen ein",
        required : "Erforderlich",
        registrationComplete : "Registrierung abgeschlossen! 🎉",
        registrationCompleteDetails : "Bitte überprüfen Sie Ihren Posteingang, um Ihre E-Mail zu bestätigen und mit der Erkundung zu beginnen.",
        unexpectedError : "Unerwarteter Fehler aufgetreten",
        tryLater : "Versuchen Sie es später",
        firstName : "Vorname",
        lastName: "Nachname",
        birthday : "Geburtsdatum",
        submit : "Senden",
        settings : "Einstellungen",
        newReservation : 'Neue Reservierung',
        addReservation : "Reservierung hinzufügen",
        logout : "Abmelden",
        darkMode: "Dunkelmodus",
        lightMode: "Hellmodus",
        reserved : "Reserviert",
        noReservation : "Keine Reservierung.",
        confirmReservation : "Reservierung bestätigen",
        confirmReservatiojnDetails : "Bitte überprüfen Sie das Datum und die Uhrzeiten",
        reservationConfirm : "Reservierung bestätigt! 🎾",
        reservationConfirmDetails: "Stellen Sie sicher, dass Sie bereit sind zu spielen und genießen Sie Ihre Zeit auf dem Platz!",
        reservationFailure : "Slot nicht verfügbar ⛔️",
        reservationFailureDetails: "Entschuldigung, der von Ihnen ausgewählte Zeitraum ist nicht mehr verfügbar. Bitte wählen Sie einen anderen Zeitraum.",
        court : "Platz",
        start : "Start",
        end: "Ende",
        minimumHour: "Mindestens 1 Stunde",
        date: "Datum"
    },
    pt: {
        locale: "pt-PT",
        welcome: "Bem-vindo",
        home: "Página inicial",
        reservation: "Reserva",
        profil: "Perfil",
        contact: "Contato",
        myInformation : "Minhas informações",
        changePassword: "Alterar senha",
        email: "E-mail",
        password : "Senha",
        confirmPassword : "Confirmar senha",
        invalidEmail : "E-mail inválido",
        invalidPassword: "Por favor, insira uma senha válida",
        passwordsNotMatch : "As senhas não coincidem",
        requiredEmail : "Por favor, insira o endereço de e-mail",
        requiredPassword : "Por favor, insira a senha",
        emailNotRegistered : "E-mail não registrado",
        emailRegistered: "E-mail já registrado",
        passwordUpdate : "Senha atualizada com sucesso! ✅",
        informationUpdated : "Informações atualizadas com sucesso! ✅",
        informationUpdatedDetails: "Não se esqueça de verificar seu endereço de e-mail se o atualizou.",
        connectionFailure : "Falha na conexão ⛔️",
        connectionFailureDetails : "Desculpe, nosso serviço não está disponível ou você não tem conexão com a internet.",
        wrongInformation : "Senha ou e-mail incorretos",
        createAccount: "Criar nova conta",
        signIn : "Entrar",
        login : "Entrar",
        register : "Registrar",
        tooShort : "Senha muito curta!",
        tooLong: "Senha muito longa!",
        requiredName : "Por favor, insira o nome completo",
        required : "Obrigatório",
        registrationComplete : "Registro completo! 🎉",
        registrationCompleteDetails : "Por favor, verifique sua caixa de entrada para confirmar seu e-mail e começar a explorar.",
        unexpectedError : "Erro inesperado ocorreu",
        tryLater : "Tente mais tarde",
        firstName : "Primeiro nome",
        lastName: "Sobrenome",
        birthday : "Data de nascimento",
        submit : "Enviar",
        settings : "Configurações",
        newReservation : 'Nova reserva',
        addReservation : "Adicionar reserva",
        logout : "Sair",
        darkMode: "Modo escuro",
        lightMode: "Modo claro",
        reserved : "Reservado",
        noReservation : "Nenhuma reserva.",
        confirmReservation : "Confirmar reserva",
        confirmReservatiojnDetails : "Por favor, verifique a data e horário",
        reservationConfirm : "Reserva confirmada! 🎾",
        reservationConfirmDetails: "Certifique-se de estar pronto para jogar e aproveite seu tempo na quadra!",
        reservationFailure : "Slot não disponível ⛔️",
        reservationFailureDetails: "Desculpe, o horário selecionado não está mais disponível. Por favor, escolha outro horário.",
        court : "Quadra",
        start : "Início",
        end: "Fim",
        minimumHour: "Mínimo de 1 hora",
        date: "Data"
    },
}

export { translations }